# fly.toml app configuration file generated for mcintoshhotshots-dev on 2025-05-22T18:57:11-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mcintoshhotshots-dev'
primary_region = 'den'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  ASPNETCORE_URLS = "http://+:80"
  ASPNETCORE_ENVIRONMENT = "Production"
